name: Debug Merge Group Context

on:
  merge_group:
  pull_request:
    types: [opened, synchronize]

jobs:
  debug-context:
    name: Debug Context (${{ github.event_name }})
    runs-on: ubuntu-latest
    steps:
      - name: Log GitHub context using shell
        run: |
          echo "=== Event Name ==="
          echo "Event: ${{ github.event_name }}"
          
          echo ""
          echo "=== Basic Info ==="
          echo "Repository: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"
          echo "SHA: ${{ github.sha }}"
          echo "Ref: ${{ github.ref }}"
          
          if [[ "${{ github.event_name }}" == "merge_group" ]]; then
            echo ""
            echo "=== Merge Group Info ==="
            echo "Head SHA: ${{ github.event.merge_group.head_sha }}"
            echo "Base Ref: ${{ github.event.merge_group.base_ref }}"
            echo "Base SHA: ${{ github.event.merge_group.base_sha }}"
            
            echo ""
            echo "=== Pull Request Info (if available) ==="
            echo "PR Number: ${{ github.event.merge_group.pull_request.number }}"
            echo "PR User: ${{ github.event.merge_group.pull_request.user.login }}"
            echo "PR Title: ${{ github.event.merge_group.pull_request.title }}"
            
            echo ""
            echo "=== Head Commit Info (if available) ==="
            echo "Commit Author: ${{ github.event.merge_group.head_commit.author.login }}"
            echo "Commit Message: ${{ github.event.merge_group.head_commit.message }}"
          fi
          
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo ""
            echo "=== Pull Request Info ==="
            echo "PR Number: ${{ github.event.pull_request.number }}"
            echo "PR User: ${{ github.event.pull_request.user.login }}"
            echo "PR Title: ${{ github.event.pull_request.title }}"
            echo "PR Action: ${{ github.event.action }}"
          fi

      - name: Log full event payload
        run: |
          echo "=== Full Event Payload ==="
          echo '${{ toJson(github.event) }}'

      - name: Log environment variables
        run: |
          echo "=== GitHub Event Variables ==="
          echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
          echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"
