name: Log Merge Group Context

on:
  merge_group:

jobs:
  log-context:
    runs-on: ubuntu-latest
    steps:
      - name: Log GitHub Context
        run: |
          echo "=== GitHub Context ==="
          echo "${{ toJson(github) }}" | jq .
      
      - name: Log Environment Variables
        run: |
          echo "=== Environment Variables ==="
          printenv | sort

      - name: Log Event Payload
        run: |
          echo "=== Event Payload ==="
          cat $GITHUB_EVENT_PATH | jq .

      - name: Log Git Commit Info
        run: |
          git log -n 5 --oneline || echo "Git log not available (no repo cloned)"

      - name: Checkout (if needed)
        uses: actions/checkout@v4
